UPDATE main.rs.
Kibalchish47/Calculator pull request #3
Opened 2022-07-27 20:08 UTC by suleymanovdev

2022-07-27 20:08 UTC, suleymanovdev commented
More designed version.

2022-07-30 12:35 UTC, istadem2077 requested changes
Added main redundant comments(DRY), and unnecessary  changes.

2022-07-30 12:35 UTC, istadem2077 commented on src/main.rs
> +            Operation::Sub  => num1 - num2, // returns num1 - num2
Unneeded absolutely, redundant. DRY.

2022-07-30 12:35 UTC, istadem2077 commented on src/main.rs
> +    println!("TEXT-BASED CALCULATOR on RUST");
Again redundant, it is pretty obvious that this program is written in Rust.

2022-07-30 12:35 UTC, istadem2077 commented on src/main.rs
> +}
Why.

2022-07-30 16:52 UTC, closed without merging